version: '3.8'

services:
  blue-db:
    image: postgres:14
    container_name: migration-blue
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production_blue
    ports:
      - "5439:5432"
    volumes:
      - blue_data:/var/lib/postgresql/data

  green-db:
    image: postgres:14
    container_name: migration-green
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production_green
    ports:
      - "5440:5432"
    volumes:
      - green_data:/var/lib/postgresql/data

volumes:
  blue_data:
  green_data:
